"""added tablenames

Revision ID: 2f4f9efa803c
Revises: b441309dd459
Create Date: 2022-12-08 14:51:37.454709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f4f9efa803c'
down_revision = 'b441309dd459'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meal_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('main', sa.String(length=30), nullable=False),
    sa.Column('snack', sa.String(length=30), nullable=False),
    sa.Column('drink', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('upVotes', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.drop_table('user')
    op.drop_table('meal')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meal',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('main', sa.VARCHAR(length=30), nullable=False),
    sa.Column('snack', sa.VARCHAR(length=30), nullable=False),
    sa.Column('drink', sa.VARCHAR(length=30), nullable=False),
    sa.Column('name', sa.VARCHAR(length=30), nullable=False),
    sa.Column('upVotes', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=20), nullable=False),
    sa.Column('password', sa.VARCHAR(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.drop_table('user_table')
    op.drop_table('meal_table')
    # ### end Alembic commands ###
