"""Many to many implemented with user_meals table

Revision ID: 950f7703e8dc
Revises: c3c4da43ff45
Create Date: 2022-12-10 14:11:04.968505

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '950f7703e8dc'
down_revision = 'c3c4da43ff45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('main', sa.String(length=30), nullable=False),
    sa.Column('snack', sa.String(length=30), nullable=False),
    sa.Column('drink', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=True),
    sa.Column('likes', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('user_meals',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('meal_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['meal_id'], ['meal.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.drop_table('user_table')
    op.drop_table('meal_table')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meal_table',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('likes', sa.INTEGER(), nullable=True),
    sa.Column('main', sa.VARCHAR(length=30), nullable=False),
    sa.Column('snack', sa.VARCHAR(length=30), nullable=False),
    sa.Column('drink', sa.VARCHAR(length=30), nullable=False),
    sa.Column('name', sa.VARCHAR(length=30), nullable=False),
    sa.Column('description', sa.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user_table',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=20), nullable=False),
    sa.Column('password', sa.VARCHAR(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.drop_table('user_meals')
    op.drop_table('user')
    op.drop_table('meal')
    # ### end Alembic commands ###
