"""Added description column

Revision ID: c3c4da43ff45
Revises: babacda10ed0
Create Date: 2022-12-08 21:41:05.438581

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3c4da43ff45'
down_revision = 'babacda10ed0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meal_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meal_table', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
